mod activemq;
mod alertmanager;
mod apache;
mod arcserve;
mod aws_vm;
mod azure_vm;
mod corosync;
mod couchbase;
mod cups;
mod db2;
mod docker;
mod domino;
mod haproxy;
mod hyperv;
mod isc_dhcpd;
mod keepalived;
mod lxc;
mod mongodb;
mod mqtt;
mod msexch;
mod mssql;
mod mysql;
mod nfs_server;
mod nginx;
mod oracle;
mod os;
mod pacemaker;
mod plesk;
mod podman;
mod postfix;
mod postgres;
mod prometheus;
mod redis;
mod sap_hana;
mod sap_netweaver;
mod skype;
mod tsm;
mod util;
mod varnish;
mod veeam;
mod veritas;
mod virtualbox_guest;
mod zerto;

pub use activemq::detect_activemq;
pub use alertmanager::detect_alertmanager;
pub use apache::detect_apache;
pub use arcserve::detect_arcserve;
pub use aws_vm::detect_aws_vm;
pub use azure_vm::detect_azure_vm;
pub use corosync::detect_corosync;
pub use couchbase::detect_couchbase;
pub use cups::detect_cups;
pub use db2::detect_db2;
pub use docker::detect_docker;
pub use domino::detect_domino;
pub use haproxy::detect_haproxy;
pub use hyperv::detect_hyperv;
pub use isc_dhcpd::detect_isc_dhcpd;
pub use keepalived::detect_keepalived;
pub use lxc::detect_lxc;
pub use mongodb::detect_mongodb;
pub use mqtt::detect_mqtt;
pub use msexch::detect_msexch;
pub use mssql::detect_mssql;
pub use mysql::detect_mysql;
pub use nfs_server::detect_nfs_server;
pub use nginx::detect_nginx;
pub use oracle::detect_oracle;
pub use os::detect_os;
pub use pacemaker::detect_pacemaker;
pub use plesk::detect_plesk;
pub use podman::detect_podman;
pub use postfix::detect_postfix;
pub use postgres::detect_postgres;
pub use prometheus::detect_prometheus;
pub use redis::detect_redis;
pub use sap_hana::detect_sap_hana;
pub use sap_netweaver::detect_sap_netweaver;
pub use skype::detect_skype;
pub use tsm::detect_tsm;
pub use util::filesystem::RealFileSystem;
pub use varnish::detect_varnish;
pub use veeam::detect_veeam;
pub use veritas::detect_veritas;
pub use virtualbox_guest::detect_virtualbox_guest;
pub use zerto::detect_zerto;
